### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by jordan-singer** [jordan-singer/BlackBird#24]
Should this read `example.State.Player`?

https://github.com/jordan-singer/BlackBird/blob/c7b6d3558b4af5b042a3fe3f781158b53b88d921/src/blackbird.py#L48

**Comment by Kevdog25** [comment]
Yes it should. I wouldn't be surprised if there were still issues in that piece of code, since I haven't actually run it :).

**Comment by Kevdog25** [comment]
This was fixed in... uhh idk.
