### ISSUE TITLE
Reuse of variables in nested generators scares me

### ISSUE THREAD

**Issue by Kevdog25** [jordan-singer/BlackBird#6]
`children_probs = [
            (child.N ** (1/self.temperature)) / sum([child.N ** (1/self.temperature) for child in self.root.children])
            for child in self.root.children]`

its not clear in this expression which iterator child is from when evaluating child.N

**Comment by jordan-singer** [comment]
Fixed in <a href="https://github.com/jordan-singer/BlackBird/commit/8b85ccb3f5e6ecad3a997c890a1bec79e90d03d2">this commit</a>.
